FROM node:18-alpine

ARG DOCKERFILE_SERVER_PORT

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN npm run build

COPY . .

EXPOSE $DOCKERFILE_SERVER_PORT

CMD ["npm", "run", "start"]